### ISSUE TITLE
[VirtualizationServerController2012] Error while converting VHD: Thread was being aborted.

### ISSUE THREAD

**Issue by berkut1** [FuseCP/SolidCP#103]
**Describe the bug**
```
Error while converting VHD: Thread was being aborted.
Thread was being aborted.
at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
at System.Threading.Thread.Sleep(Int32 millisecondsTimeout)
at SolidCP.EnterpriseServer.VirtualizationServerController2012.JobCompleted(VirtualizationServer2012 vs, ConcreteJob job)
at SolidCP.EnterpriseServer.VirtualizationServerController2012.CreateVirtualMachineInternal(String taskId, VirtualMachine vm, LibraryItem osTemplate, Int32 externalAddressesNumber, Boolean randomExternalAddresses, Int32[] externalAddresses, Int32 privateAddressesNumber, Boolean randomPrivateAddresses, String[] privateAddresses, String summaryLetterEmail)
Unhandled error while creating VPS: Thread was being aborted.
Thread was being aborted.
at SolidCP.EnterpriseServer.VirtualizationServerController2012.CreateVirtualMachineInternal(String taskId, VirtualMachine vm, LibraryItem osTemplate, Int32 externalAddressesNumber, Boolean randomExternalAddresses, Int32[] externalAddresses, Int32 privateAddressesNumber, Boolean randomPrivateAddresses, String[] privateAddresses, String summaryLetterEmail)
VPS was not created
```

**Possible solution**
Wrap the JobCompleted function in a try catch and if we get an exception, check the JobState, if JobState is fine then continue, if not, then complete the task and show an error.

**To Reproduce**
random

**SolidCP Info**
 - SolidCP Version: any

**Comment by berkut1** [comment]
This issue still exist.
After thread aborted need to reactivate it, or we still get exception if try to get job state
https://github.com/FuseCP/SolidCP/blob/5a9b9285d8a23d089321d981090ae138b6c75c46/SolidCP/Sources/SolidCP.EnterpriseServer.Code/Virtualization2012/Helpers/JobHelper.cs#L30

Need find a way how to test the best solution.

**Comment by berkut1** [comment]
I guess this issue was fixed by using a safer way to track jobs.
https://github.com/FuseCP/SolidCP/pull/221
