### ISSUE TITLE
[HyperV2012R2+] Can't find a job ID

### ISSUE THREAD

**Issue by berkut1** [FuseCP/SolidCP#146]
**Describe the bug**
An extremally rare error while converting VHD

**SolidCP Info**
 - SolidCP Version:  Any

**Additional context**
When this error occurs, Windows still continues to convert the VHD, we just lost a job, that provide data to use that task.
```
Error while converting VHD: Server was unable to process request. ---> Invoke error: The command cannot find a job with the job ID 2. Verify the value of the Id parameter and then try the command again.
Server was unable to process request. ---> Invoke error: The command cannot find a job with the job ID 2. Verify the value of the Id parameter and then try the command again.
at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
at System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters)
at SolidCP.Providers.Virtualization2012.VirtualizationServer2012.GetJob(String jobId)
at SolidCP.EnterpriseServer.Code.Virtualization2012.Helpers.JobHelper.JobCompleted(VirtualizationServer2012 vs, ConcreteJob job, Boolean resetProgressBarIndicatorAfterFinish)
at SolidCP.EnterpriseServer.Code.Virtualization2012.Helpers.JobHelper.TryJobCompleted(VirtualizationServer2012 vs, ConcreteJob job, Boolean resetProgressBarIndicatorAfterFinish)
at SolidCP.EnterpriseServer.Code.Virtualization2012.Tasks.CreateVirtualMachineTask.CreateVirtualMachineInternal(String taskId, VirtualMachine vm, LibraryItem osTemplate, Int32 externalAddressesNumber, Boolean randomExternalAddresses, Int32[] externalAddresses, Int32 privateAddressesNumber, Boolean randomPrivateAddresses, String[] privateAddresses, String summaryLetterEmail)
```

**Possible solutions**
- Catch this exception and try to simulated a job with checking the VHD space change, if it still keeps growing then the VHD conversion is working.
- Replace PowerShell converting commands into WMI, where exist more stable methods with async job tasks.

**Comment by berkut1** [comment]
I have an idea that can be implemented using WMI, as well as finding lost jobs using WMI. I will try this in January/February.

**Comment by berkut1** [comment]
Fixed in https://github.com/FuseCP/SolidCP/pull/221
