### ISSUE TITLE
Deadlock transaction

### ISSUE THREAD

**Issue by berkut1** [FuseCP/SolidCP#56]
**Describe the bug**
When we remove a hosting space with items, we can get a deadlock transaction, where items are deleted on the server side, but Enterprise does not know about it and will still store this information in the DB..

**To Reproduce**
There is no 100% way to reproduce it, just happens once per some years.

**SolidCP Info**
 - SolidCP Version:  all versions (latest 1.4.7)

**Appears**
- PackageAsyncWorker.DeletePackagesServiceItems() (**fixed in 1.4.8**)
- SolidCP.EnterpriseServer.TaskManager.CompleteTask() (possible fixed in 1.5.0 with SQL indexes)
- EnterpriseServer.ObjectUtils.FillCollectionFromDataReader() (need more details after 1.5.0)
- Somewhere else?

**Logs**

```
Process ID: 8068

Exception: System.Data.SqlClient.SqlException

Message: Transaction (Process ID 52) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

StackTrace:    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteNonQuery(SqlConnection connection, CommandType commandType, String commandText, SqlParameter[] commandParameters)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteNonQuery(String connectionString, CommandType commandType, String commandText, SqlParameter[] commandParameters)
   at SolidCP.EnterpriseServer.PackageAsyncWorker.DeletePackagesServiceItems()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

```
Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Data.SqlClient.SqlException
   at System.Data.SqlClient.SqlConnection.OnError(System.Data.SqlClient.SqlException, Boolean, System.Action`1<System.Action>)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(System.Data.SqlClient.TdsParserStateObject, Boolean, Boolean)
   at System.Data.SqlClient.TdsParser.TryRun(System.Data.SqlClient.RunBehavior, System.Data.SqlClient.SqlCommand, System.Data.SqlClient.SqlDataReader, System.Data.SqlClient.BulkCopySimpleResultSet, System.Data.SqlClient.TdsParserStateObject, Boolean ByRef)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(System.Data.SqlClient.SqlDataReader, System.Data.SqlClient.RunBehavior, System.String, Boolean, Boolean, Boolean)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(System.Data.CommandBehavior, System.Data.SqlClient.RunBehavior, Boolean, Boolean, Int32, System.Threading.Tasks.Task ByRef, Boolean, Boolean, System.Data.SqlClient.SqlDataReader, Boolean)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(System.Data.CommandBehavior, System.Data.SqlClient.RunBehavior, Boolean, System.String, System.Threading.Tasks.TaskCompletionSource`1<System.Object>, Int32, System.Threading.Tasks.Task ByRef, Boolean ByRef, Boolean, Boolean)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(System.Threading.Tasks.TaskCompletionSource`1<System.Object>, System.String, Boolean, Int32, Boolean ByRef, Boolean, Boolean)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteNonQuery(System.Data.SqlClient.SqlConnection, System.Data.CommandType, System.String, System.Data.SqlClient.SqlParameter[])
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteNonQuery(System.String, System.Data.CommandType, System.String, System.Data.SqlClient.SqlParameter[])
   at SolidCP.EnterpriseServer.PackageAsyncWorker.DeletePackagesServiceItems()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

`A process serving application pool 'SolidCP Enterprise Server Pool' suffered a fatal communication error with the Windows Process Activation Service. The process id was '8068'. The data field contains the error number.`

```
Faulting application name: w3wp.exe, version: 10.0.14393.0, time stamp: 0x57899b8a
Faulting module name: KERNELBASE.dll, version: 10.0.14393.3986, time stamp: 0x5f77fd5b
Exception code: 0xe0434352
Fault offset: 0x0000000000034f38
Faulting process id: 0x1f84
Faulting application start time: 0x01d6f50d45397058
Faulting application path: c:\windows\system32\inetsrv\w3wp.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 75fb10e3-e397-48f9-b903-6978d52a2789
Faulting package full name: 
Faulting package-relative application ID: 

```

**Comment by berkut1** [comment]
The Deadlock transaction can take 30-60 seconds, and everything that has been done during this time won't be saved to the DB, but will be executed on the server, so the DB will be outdated.

**Comment by berkut1** [comment]
New deadlock logs:
ASP.NET 4.0
```
An unhandled exception occurred and the process was terminated.

Application ID: /LM/W3SVC/1/ROOT

Process ID: 6172

Exception: System.Data.SqlClient.SqlException

Message: Transaction (Process ID 61) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

StackTrace:    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at SolidCP.EnterpriseServer.ObjectUtils.FillCollectionFromDataReader[T](List`1 list, IDataReader reader)
   at SolidCP.EnterpriseServer.TaskController.GetLogs(BackgroundTask task, DateTime startLogTime)
   at SolidCP.EnterpriseServer.TaskManager.AddAuditLog(BackgroundTask task)
   at SolidCP.EnterpriseServer.TaskManager.CompleteTask()
   at SolidCP.EnterpriseServer.VirtualizationServerController2012.ReinstallVirtualMachineInternal(Int32 itemId, VirtualMachine VMSettings, String adminPassword, String[] privIps, Boolean saveVirtualDisk, Boolean exportVps, String exportPath)
   at SolidCP.EnterpriseServer.Code.Virtualization2012.VirtualizationAsyncWorker2012.ReinstallVPS()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
.NET Runtime
```
Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Data.SqlClient.SqlException
   at System.Data.SqlClient.SqlConnection.OnError(System.Data.SqlClient.SqlException, Boolean, System.Action`1<System.Action>)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(System.Data.SqlClient.TdsParserStateObject, Boolean, Boolean)
   at System.Data.SqlClient.TdsParser.TryRun(System.Data.SqlClient.RunBehavior, System.Data.SqlClient.SqlCommand, System.Data.SqlClient.SqlDataReader, System.Data.SqlClient.BulkCopySimpleResultSet, System.Data.SqlClient.TdsParserStateObject, Boolean ByRef)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean ByRef)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean, Boolean ByRef)
   at System.Data.SqlClient.SqlDataReader.Read()
   at SolidCP.EnterpriseServer.ObjectUtils.FillCollectionFromDataReader[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.List`1<System.__Canon>, System.Data.IDataReader)
   at SolidCP.EnterpriseServer.TaskController.GetLogs(SolidCP.EnterpriseServer.BackgroundTask, System.DateTime)
   at SolidCP.EnterpriseServer.TaskManager.AddAuditLog(SolidCP.EnterpriseServer.BackgroundTask)
   at SolidCP.EnterpriseServer.TaskManager.CompleteTask()
   at SolidCP.EnterpriseServer.VirtualizationServerController2012.ReinstallVirtualMachineInternal(Int32, SolidCP.Providers.Virtualization.VirtualMachine, System.String, System.String[], Boolean, Boolean, System.String)
   at SolidCP.EnterpriseServer.Code.Virtualization2012.VirtualizationAsyncWorker2012.ReinstallVPS()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```
Application Error:
```
Faulting application name: w3wp.exe, version: 10.0.17763.1, time stamp: 0xcfdb13d8
Faulting module name: KERNELBASE.dll, version: 10.0.17763.1911, time stamp: 0x206fb2f7
Exception code: 0xe0434352
Fault offset: 0x0000000000039689
Faulting process id: 0x181c
Faulting application start time: 0x01d749defdee18fe
Faulting application path: c:\windows\system32\inetsrv\w3wp.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 2657e793-aede-493e-b6d0-b70f15dda8c7
Faulting package full name: 
Faulting package-relative application ID: 
```

_Originally posted by @FeEzioXIII in https://github.com/FuseCP/SolidCP/issues/71#issuecomment-841861560_

**Comment by berkut1** [comment]
With changes for 1.5.0 I can say that we haven't got any more deadlock transactions.
Need to wait a feedback from @FeEzioXIII or from other people after update 1.5.0.
